version: 2.1
orbs:
  node:circleci/node@5.1.0

executors:
  my-exe:
    docker:
      - image: cimg/node:19.8.0
        auth:
          username: $DOCKER_HUB_URER
          password: $DOCKER_HUB_PASSWORD

jobs:
  test:
    executor: my-exe
    steps:
      - checkout
      - run: npm install
      - run: npm rebuild
      - run test

workflows:
    my-workflow:
      jobs:
        - test
